---
title: "2021_MARSSModel"
output: pdf_document
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(lubridate)
library(patchwork)
library(astsa)
library(forecast)
library(dplyr)
library(pander)
library(MARSS)
library(MASS)
library(gridExtra)
library(weathermetrics)
```

##Read in data
```{r}
daily_means_long <- readRDS('daily_means_long.rds')
covariate <- readRDS('covariate.rds')
```

##Data Matrix 
```{r, include = F}
#Convert data to matrix and z-score
transformed_dat <- as.matrix(daily_means_long)
transformed_dat <- zscore(transformed_dat)
saveRDS(transformed_dat,"transformed_dat.rds")

```

##Covariates
```{r, include=FALSE}
#Build the little c matrix, call it matrixc
matrixc <- matrix(nrow=1,ncol=378)
matrixc <- (as.matrix(covariate))
saveRDS(matrixc,"matrixc.rds")

```

###Check data and covariates
```{r, include = F}
matplot(t(transformed_dat))
matplot(t(matrixc))

#looks okay, we removed AP2 in the visualization .rmd file
```

##Z-Matrices
```{r }
#Hypothesis 1: All ponds and creeks are separate
matrix2 <- matrix(nrow=25,ncol=11)
matrix2[c(1:2),1] <- 1 #Alexander
matrix2[c(1:2),c(2:11)] <- 0
matrix2[c(4:5),2] <- 1 #Stender
matrix2[c(4:5),c(1,3:11)] <- 0 
matrix2[c(3,6,9,11),3] <- 1 #Seiad Creek
matrix2[c(3,6,9,11),c(1,2,4:11)] <- 0
matrix2[7,4] <- 1 #Durazo
matrix2[7,c(1:3,5:11)] <- 0
matrix2[8,5] <- 1 #Lower Seiad
matrix2[8,c(1:4,6:11)] <- 0
matrix2[10,6] <- 1 #May
matrix2[10,c(1:5,7:11)] <- 0
matrix2[c(12:13),7] <- 1 #Fish Gulch
matrix2[c(12:13),c(1:6,8:11)] <- 0
matrix2[c(15:17),8] <- 1 #Goodman
matrix2[c(15:17),c(1:7,9:11)] <- 0
matrix2[c(19:21),9] <- 1 #Upper Lawrence
matrix2[c(19:21),c(1:8,10:11)] <- 0
matrix2[c(23:25),10] <- 1 #Lower Lawrence
matrix2[c(23:25),c(1:9,11)] <- 0
matrix2[c(14,18,22),11] <- 1 #Horse Creek
matrix2[c(14,18,22),c(1:10)] <- 0

#Hypothesis 2: ponds versus creeks
matrix3 <- matrix(nrow=25, ncol=2)
matrix3[c(1:2,4:5,7:8,10,12:13,15:17,19:21,23:25),1] <- 1 #All ponds
matrix3[c(1:2,4:5,7:8,10,12:13,15:17,19:21,23:25),2] <- 0
matrix3[c(3,6,9,11,14,18,22),1] <- 0 #All creeks
matrix3[c(3,6,9,11,14,18,22),2] <- 1

#Hypothesis 3: tributary versus tributary
matrix4 <-matrix(nrow=25,ncol=4)
matrix4[c(1:2,4:5,7:8,10),1] <- 1  #Seiad Creek Ponds
matrix4[c(1:2,4:5,7:8,10),c(2:4)] <- 0
matrix4[c(3,6,9,11),2] <- 1 #Seiad Creek
matrix4[c(3,6,9,11),c(1,3:4)] <- 0
matrix4[c(12:13,15:17,19:21,23:25),3] <- 1 #Horse Creek Ponds
matrix4[c(12:13,15:17,19:21,23:25),c(1,2,4)] <- 0
matrix4[c(14,18,22),4] <- 1 #Horse Creek
matrix4[c(14,18,22),c(1:3)] <- 0

#Hypothesis 4: All sensors are the same
matrix5 <-  matrix(nrow=25, ncol=1)
matrix5[,] <- 1

saveRDS(matrix2,"matrix2.rds")
saveRDS(matrix3,"matrix3.rds")
saveRDS(matrix4,"matrix4.rds")
saveRDS(matrix5,"matrix5.rds")
```

##MARSS models
```{r}
#Hypothesis 1, Model 1: all separate
mod11 = list()
mod11$A = "zero" #no trend because we z scored
mod11$Z = matrix2
mod11$R = "diagonal and equal" #all the sensors are same, so observation error should be same
mod11$Q = "diagonal and unequal" 
mod11$B = "identity" #assuming no species interactions
mod11$U = "zero" #no trend because we z scored 
mod11$C = "unequal" #Can set C to unequal because it is going off the Z matrix where I have already indicated how to split up the sites.
mod11$c = matrixc
mod11.fit = MARSS(transformed_dat, model=mod11, control=list(maxit=10000))
mod11.params = MARSSparamCIs(mod11.fit)
saveRDS(mod11.fit,"mod11.fit.rds")
saveRDS(mod11.params,"mod11.params.rds")

par(mfrow=c(5,2), mai=c(0.1,0.5,0.2,0.1), omi=c(0.5,0,0,0))
  for (j in 1:5) {
    plot.ts(residuals<-MARSSresiduals(mod11.fit, type = "tt1")$model.residuals[j, ],
            ylab = "Residual")
    abline(h = 0, lty = "dashed")
    acf(residuals,na.action = na.pass)
  }

#Hypothesis 2, Model 3: ponds vs. creeks 
mod12 <- mod11 
mod12$Z <- matrix3
mod12.fit = MARSS(transformed_dat, model=mod12, control=list(maxit=10000))
mod12.params = MARSSparamCIs(mod12.fit)
saveRDS(mod12.fit,"mod12.fit.rds")
saveRDS(mod12.params,"mod12.params.rds")

#Hypothesis 3, Model 3: Tributary versus tributary
mod13 <- mod11
mod13$Z = matrix4
mod13.fit = MARSS(transformed_dat, model=mod13, control=list(maxit=10000))
mod13.params = MARSSparamCIs(mod13.fit)
saveRDS(mod13.fit,"mod13.fit.rds")
saveRDS(mod13.params,"mod13.params.rds")

#Hypothesis 4, Model 4: All same
mod14 <- mod11
mod14$Z <- matrix5
mod14.fit = MARSS(transformed_dat, model=mod14, control=list(maxit=10000))
mod14.params =MARSSparamCIs(mod14.fit)
saveRDS(mod14.fit,"mod14.fit.rds")
saveRDS(mod14.params,"mod14.params.rds")
```

###AICc 
```{r}
data.frame(Model=c("Model11", "Model12", "Model13", "Model14"),
           AICc=round(c(mod11.fit$AICc,
                        mod12.fit$AICc,
                        mod13.fit$AICc,
                        mod14.fit$AICc),1))
```

