---
title: "2021_KBMPFigures"
output: html_document
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(lubridate)
library(patchwork)
library(astsa)
library(forecast)
library(dplyr)
library(pander)
library(MARSS)
library(MASS)
library(gridExtra)
library(weathermetrics)
library(magick)
library(reshape2)
library(RColorBrewer)
library(colorspace)
library(grid)
library(cowplot)
```

##Read in data
```{r}
day <- seq(mdy('7/1/2020'),mdy('7/13/2021'),by = "day") 
day <- as.data.frame(day) #convert "day" to data frame

daily_means_long <- readRDS('daily_means_long.rds')
daily_max_long <- readRDS("daily_max_long.rds")
daily_min_long <- readRDS("daily_min_long.rds")

data <- as.data.frame(t(daily_means_long))
data <- cbind(data,day)
datamax <- as.data.frame(t(daily_max_long))
datamax <- cbind(datamax,day)
datamin <- as.data.frame(t(daily_min_long))
datamin <- cbind(datamin,day)

covariate <- readRDS("covariate.rds")

seiadcreek <- read.csv('SeiadCreek_Historical.csv')
seiadcreek$date <- lubridate::mdy_hm(seiadcreek$Date_Time)
klamath <- read.csv('Klamath_Historical.csv')
klamath$date <- lubridate::mdy_hm(klamath$Date_Time)

```

#MARSS Model
```{r}
#Format data long
data_long <- gather(data, site, value, -day)

#All sites
png("Fig_Full_TimeSeries.png", width = 900, height = 400)
ggplot()+
  geom_line(data = data_long, aes(x = day, value, col = site))+
  labs(x = "Date",
       y = "Temperature (oC)")+
  theme_classic()+
  theme(text=element_text(size=25), legend.position = "none")
dev.off()
```

#Blue Ponds
```{r}
#Seiad Creek + Ponds all blue
ggplot(subset(data_long, site %in% c("MayCk","AP1","SP1","Durazo","LS","May")))+
  geom_line(aes(x = day, value, col = site))+
  labs(x = "Date",
       y = "Temperature (oC)")+
  theme_classic()+
  scale_color_manual(values = brewer.pal(6,"Blues"))+
  theme(text=element_text(size=25))

#Seiad Creek + Ponds colorful
color1 <- brewer.pal(5,"Blues")
color2 <- "salmon"

```

#HOT Klamath and Seiad Creek temperatures
```{r}
#Clean up Klamath time series
klamath$halfhour <- lubridate::floor_date(klamath$date, unit="30 min")
klamath <- klamath %>%filter(date>"2010-12-16"& date < "2017-11-02")
klamath <- tidyr::complete(klamath, halfhour = seq(as.POSIXct("2010-12-16"), as.POSIXct("2017-11-02"),by = "30 min"))
tail(klamath)

#Clean up Seiad Creek time series
seiadcreek$hour <- lubridate::floor_date(seiadcreek$date, unit="hour")
seiadcreek <- seiadcreek %>%filter(date>"2010-12-16"& date < "2017-11-02")
seiadcreek <- tidyr::complete(seiadcreek, hour = seq(as.POSIXct("2010-12-16"), as.POSIXct("2017-11-02"),by = "hour"))

png("Fig_Klamath_SeiadCk.png", width = 900, height = 400)
ggplot()+
  geom_line(data = klamath, aes(x = halfhour, y = Temp, color = "Klamath"))+
  geom_line(data = seiadcreek, aes(x = hour, y = Temp, color = "Seiad Creek"))+
  labs(x = "Year",
       y = "Temperature (C)")+
  theme_classic()+
  theme(text=element_text(size=20), legend.position = "bottom")+
  scale_colour_manual("", values = c("Klamath"="gold", "Seiad Creek"="salmon")) +
  scale_y_continuous("Temperature (C)", limits = c(0,30), breaks = 5*0:30) 
dev.off()
```
#Summer boxplots
```{r}
#Format data long
data_max_long <- gather(datamax, site, value, -day)
data_summer <- data_max_long %>%filter(day>'2020-07-15'& day < '2020-09-15')

png("Fig_Seiad_Boxplot.png", width = 500, height = 400)
ggplot(subset(data_summer, site %in% c("AP1","SP2","Durazo","LS","May","SPck")))+
  geom_boxplot(aes(x = site, value, col = day))+
  theme_classic()+
  theme(text=element_text(size=20))+
  scale_x_discrete(name ="Site", 
                   limits = c("AP1","SP2","Durazo","LS","May","SPck"),
                    labels=c("AP1" = "Alexander","SP2"= "Stender","Durazo"=
                               "Durazo","LS" = "LowerSeiad","May"="May","SPck" = "SeiadCreek"))+
  scale_y_continuous(name="Temperature (C)",limits=c(12.5, 22.5))
dev.off()

png("Fig_Horse_Boxplot.png", width = 500, height = 400)
ggplot(subset(data_summer, site %in% c("FG3","UL1","LL2","GP2","ULck")))+
  geom_boxplot(aes(x = site, value, col = day))+
  theme_classic()+
  theme(text=element_text(size=20))+
  scale_x_discrete(name ="Site", 
                   limits = c("FG3","UL1","LL2","GP2","ULck"),
                    labels=c("FG3" = "FishGulch","UL1"= "UpperLaw","LL2"=
                               "LowerLaw","GP2" = "Goodman","ULck"="HorseCreek"))+
  scale_y_continuous(name="Temperature (C)",limits=c(12.5, 22.5))
dev.off()

```

#Winter boxplots
```{r}
#Format data long
data_min_long <- gather(datamin, site, value, -day)
data_winter <- data_min_long %>%filter(day>'2020-12-15'& day < '2021-02-15')

png("Fig_Seiad_WinterBoxplot.png", width = 500, height = 400)
ggplot(subset(data_winter, site %in% c("AP1","SP2","Durazo","LS","May","SPck")))+
  geom_boxplot(aes(x = site, value, col = day))+
  theme_classic()+
  theme(text=element_text(size=20))+
  scale_x_discrete(name ="Site", 
                   limits = c("AP1","SP2","Durazo","LS","May","SPck"),
                    labels=c("AP1" = "Alexander","SP2"= "Stender","Durazo"=
                               "Durazo","LS" = "LowerSeiad","May"="May","SPck" = "SeiadCreek"))+
  scale_y_continuous(name="Temperature (C)", limits = c(4,12))
dev.off()

png("Fig_Horse_WinterBoxplot.png", width = 500, height = 400)
ggplot(subset(data_winter, site %in% c("FG3","UL1","LL2","GP2","ULck")))+
  geom_boxplot(aes(x = site, value, col = day))+
  theme_classic()+
  theme(text=element_text(size=20))+
  scale_x_discrete(name ="Site", 
                   limits = c("FG3","UL1","LL2","GP2","ULck"),
                    labels=c("FG3" = "FishGulch","UL1"= "UpperLaw","LL2"=
                               "LowerLaw","GP2" = "Goodman","ULck"="HorseCreek"))+
  scale_y_continuous(name="Temperature (C)", limits = c(4,12))
dev.off()

```

#Creeks and Ponds are different
```{r}
png("Fig_Seiad_TimeSeries.png", width = 500, height = 400)
ggplot()+
  geom_line(data = subset(data_long, site %in% c("AP1","SP1","Durazo","LS","May", "LSck")), aes(x = day, value, col = site))+
  labs(x = "Date",
       y = "Temperature (oC)")+
  theme_classic()+
  theme(text=element_text(size=20))
dev.off()

png("Fig_Horse_TimeSeries.png", width = 500, height = 400)
ggplot()+
  geom_line(data = subset(data_long, site %in% c("FG1","UL1","LL2","GP2","ULck")), aes(x = day, value, col = site))+
  labs(x = "Date",
       y = "Temperature (oC)")+
  theme_classic()+
  theme(text=element_text(size=20))
dev.off()
```

#Summer: Ponds are cooler than creeks
```{r}
data_summer <- data_long %>%filter(day>'2020-07-15'& day < '2020-09-15')
png("Fig_Horse_Summer.png", width = 500, height = 400)
ggplot()+
  geom_line(data = subset(data_summer, site %in% c("FG1","UL1","LL2","GP2","ULck")), aes(x = day, value, col = site))+
  labs(x = "Date",
       y = "Temperature (oC)")+
  theme_classic()+
  theme(text=element_text(size=20))
dev.off()

data_summer <- data_long %>%filter(day>'2020-07-15'& day < '2020-09-15')
png("Fig_Seiad_Summer.png", width = 500, height = 400)
ggplot()+
  geom_line(data = subset(data_summer, site %in% c("AP1","SP1","Durazo","LS","May", "MayCk")), aes(x = day, value, col = site))+
  labs(x = "Date",
       y = "Temperature (oC)")+
  theme_classic()+
  theme(text=element_text(size=20))
dev.off()
```

